"""修改了user.py

Revision ID: 39804de66855
Revises: c61f953f42da
Create Date: 2026-05-23 19:10:18.696583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39804de66855'
down_revision: Union[str, Sequence[str], None] = 'c61f953f42da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token', sa.String(length=512), nullable=True))
    op.drop_column('users', 'reset_token_jti')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token_jti', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###
